server:
  port: 3000

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://db:5432/bankmonitor
    username: user
    password: pass
  sql:
    init:
      mode: always
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

